name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
      - run: zig build test
